### ISSUE TITLE
Data code

### ISSUE THREAD

**Issue by LePetitNewbie** [nickseah1/2021-NFL-Fantasy-Draft-Rankings#1]
Hi Nick, 
         I was wondering if there was any chance for you to add the scraping code (to show how you get the data on the csv file?)
I have no experience in coding. hope thats ok. anyways this looks great. take care

Ol

**Comment by nickseah1** [comment]
Hi LePetitNewbie,

The data used for this project is from https://www.pro-football-reference.com/years/2020/fantasy.htm 

There is an option to get the table as a CSV file which I copy-pasted into Excel. From there if you go to the Data tab, then text to columns, and select commas as the delimiter it will separate everything into a nice format which you can save as a CSV file.

If you are interested in web scraping data, I would look into the Beautiful Soup Library on python. While the code for scraping data will change depending on the website, I have uploaded an example at the link below, hope this helps.

https://github.com/nickseah1/DS/blob/gh-pages/Web%20Scraping%20NCAA%20Stats.ipynb

-Nick

**Comment by LePetitNewbie** [comment]
Hi Nick
    Thanks for your reply. Appreciate your help. I will check on it.  This will definitely help. 

cheers
Ol
